# Author: Liu <lightserver.cn@gmail.com>
# Date: 2024-12-01
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../docker-compose/volumes/postgres:/var/lib/postgresql/data/pgdata:rw

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8082:8080

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - ../docker-compose/volumes/redis:/data:rw

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

  golang:
    image: golang:1.23.3-alpine3.20
    container_name: golang
    hostname: golang
    restart: always
    command:
      - /usr/local/bin/server
    environment:
      - ENV=test
      - GOPROXY=https://goproxy.cn,direct
      - GO111MODULE=on
      - TIMEZONE=Asia/Shanghai
    ports:
      - 8080:8080
    volumes:
      - ../server:/usr/local/bin/server:ro
      - ../config:/usr/local/config:ro
      - ../runtime:/runtime:rw
