app_name: wallet-service
app_version: 1.0.0
app_mode: debug
api_addr: 0.0.0.0:8080

db:
  driver: postgres
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  db_name: postgres
  init_table: true

db-test:
  driver: postgres
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  db_name: test_postgres
  init_table: false

redis:
  addr: redis:6379
  password:
  db: 0

log:
  file_path: /runtime/log
  file_ext: log
  info_filename: info
  warn_filename: warn
  err_filename: err
